server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  servlet:
    context-path: /pizza/api  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/propizza_db
    username: pizzauser
    password: pizzaadmin
    driver-class-name: org.postgresql.Driver
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-ıd:  641912812258-s5s9fkep33bshimicsnqf8noanvesob4.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#            - email
#            - profile
#             
       
          
        
            
logging:
  file:
    name: logs/prorent.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  
  level:
    org.springframework.web: DEBUG
    com.prorent: DEBUG
    org.hibernate: DEBUG
  
    
propizza:
  app:
    jwtSecret: propizza
    #60*60*24*1000
    jwtExpirationMs: 86400000     
    
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'metrics', 'logfile', 'loggers', 'beans', 'threaddump','auditevents']
  info:
    env:
      enabled: true

info:
  application:
    name: 'Propizza App'
    description: This is Propizza App
    version: '@project.version@'    

